### ISSUE TITLE
cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by frafra** [mitsuhiko/rye#126]
### Steps to Reproduce

1. Use python3.8
2. Install pipx
3. `pipx install rye`
4. Run `rye`

### Expected Result

Some help text maybe?

### Actual Result

```
Traceback (most recent call last):
  File "/home/user/.local/bin/rye", line 5, in <module>
    from rye.__main__ import cli
  File "/home/user/.local/pipx/venvs/rye/lib/python3.8/site-packages/rye/__main__.py", line 4, in <module>
    from settingscascade import SettingsManager
  File "/home/user/.local/pipx/venvs/rye/lib/python3.8/site-packages/settingscascade/__init__.py", line 2, in <module>
    from settingscascade.manager import SettingsManager
  File "/home/user/.local/pipx/venvs/rye/lib/python3.8/site-packages/settingscascade/manager.py", line 4, in <module>
    from jinja2 import Environment
  File "/home/user/.local/pipx/venvs/rye/lib/python3.8/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/user/.local/pipx/venvs/rye/lib/python3.8/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/home/user/.local/pipx/venvs/rye/lib/python3.8/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/home/user/.local/pipx/venvs/rye/lib/python3.8/site-packages/jinja2/utils.py", line 642, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/user/.local/pipx/venvs/rye/lib/python3.8/site-packages/markupsafe/__init__.py)
```

### Version Info

0.6.1

**Comment by frafra** [comment]
Sorry, that is invalid, as rye is a different software on pypi.
