### ISSUE TITLE
Using `rye install` on packages that use `setuptools` results in an error

### ISSUE THREAD

**Issue by Woovie** [mitsuhiko/rye#323]
### Steps to Reproduce

```
rye install gradio
gradio
```

### Expected Result

A successful execution

### Actual Result

```
% gradio
Traceback (most recent call last):
  File "/home/jbanasik/.rye/shims/gradio", line 5, in <module>
    from gradio.cli import cli
  File "/home/jbanasik/.rye/tools/gradio/lib/python3.11/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/jbanasik/.rye/tools/gradio/lib/python3.11/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/jbanasik/.rye/tools/gradio/lib/python3.11/site-packages/gradio/components/annotated_image.py", line 14, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "/home/jbanasik/.rye/tools/gradio/lib/python3.11/site-packages/gradio/components/base.py", line 30, in <module>
    from gradio.blocks import Block, BlockContext
  File "/home/jbanasik/.rye/tools/gradio/lib/python3.11/site-packages/gradio/blocks.py", line 25, in <module>
    from gradio import (
  File "/home/jbanasik/.rye/tools/gradio/lib/python3.11/site-packages/gradio/networking.py", line 17, in <module>
    from gradio.routes import App
  File "/home/jbanasik/.rye/tools/gradio/lib/python3.11/site-packages/gradio/routes.py", line 26, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### Version Info

```
rye 0.7.0
commit: 0.7.0 (ce17cf574 2023-06-12)
platform: linux (x86_64)
self-python: cpython@3.10
symlink support: true
```

**Comment by Woovie** [comment]
A workaround by @bluss was noted on Discord:

```
rye init rembg-fix
cd rembg-fix
rye add rembg
rye add setuptools

# Now install our new sandwich of two packages
rye install . --include-dep rembg
```

**Comment by Woovie** [comment]
I'm not sure rye will have a solution for this, but I filed an issue in case there is potentially a way to work around this. I was thinking maybe some --modify flag or something so that you can install additional packages to an existing install.
