### ISSUE TITLE
Windows 11 environment seems to be getting misconfigured

### ISSUE THREAD

**Issue by BruceEckel** [mitsuhiko/rye#349]
### Steps to Reproduce

Following instructions here: https://rye-up.com/guide/basics/. Steps and results shown in output, below.

Note that I seem unable to run `rye shell`

### Expected Result

To be able to import `flask` after adding it and syncing.

Also `rye shell` gives an error message, see bottom of "actual result"

### Actual Result

```
PS C:\git\python-experiments\actors> rye init my-project
success: Initialized project in C:\git\python-experiments\actors\my-project
  Run `rye sync` to get started
PS C:\git\python-experiments\actors> cd .\my-project\
PS C:\git\python-experiments\actors\my-project> rye sync
Initializing new virtualenv in C:\git\python-experiments\actors\my-project\.venv
Python version: cpython@3.11.3
Generating production lockfile: C:\git\python-experiments\actors\my-project\requirements.lock
Generating dev lockfile: C:\git\python-experiments\actors\my-project\requirements-dev.lock
Installing dependencies
Looking in indexes: https://pypi.org/simple/
Obtaining file:///. (from -r C:\Users\bruce\AppData\Local\Temp\tmpk6wiyniw (line 1))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: my-project
  Building editable for my-project (pyproject.toml) ... done
  Created wheel for my-project: filename=my_project-0.1.0-py3-none-any.whl size=1072 sha256=3bb2ecff1697dc1ebb66106189b1c53fd345edd23a894b661ab9e9ab07c02099
  Stored in directory: C:\Users\bruce\AppData\Local\Temp\pip-ephem-wheel-cache-mcozs8c9\wheels\97\54\f5\d849319cdfa096e074df352654ee2e7c919da8951f090690c6
Successfully built my-project
Installing collected packages: my-project
Successfully installed my-project-0.1.0
Done!
PS C:\git\python-experiments\actors\my-project> rye add "flask>=2.0"
Added flask>=2.0 as regular dependency
PS C:\git\python-experiments\actors\my-project> sync
sync: The term 'sync' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\git\python-experiments\actors\my-project> rye sync
Reusing already existing virtualenv
Generating production lockfile: C:\git\python-experiments\actors\my-project\requirements.lock
Generating dev lockfile: C:\git\python-experiments\actors\my-project\requirements-dev.lock
Installing dependencies
Found existing installation: my-project 0.1.0
Uninstalling my-project-0.1.0:
  Successfully uninstalled my-project-0.1.0
Looking in indexes: https://pypi.org/simple/
Obtaining file:///. (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 4))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting blinker==1.6.2 (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 1))
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting click==8.1.3 (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 2))
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting colorama==0.4.6 (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 3))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting flask==2.3.2 (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 5))
  Downloading Flask-2.3.2-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 1.1 MB/s eta 0:00:00
Collecting itsdangerous==2.1.2 (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 6))
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting jinja2==3.1.2 (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 7))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting markupsafe==2.1.3 (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 8))
  Using cached MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl (17 kB)
Collecting werkzeug==2.3.6 (from -r C:\Users\bruce\AppData\Local\Temp\tmpofflpvy0 (line 9))
  Downloading Werkzeug-2.3.6-py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.5/242.5 kB 3.0 MB/s eta 0:00:00
Building wheels for collected packages: my-project
  Building editable for my-project (pyproject.toml) ... done
  Created wheel for my-project: filename=my_project-0.1.0-py3-none-any.whl size=1085 sha256=f7f4ccd3f1db7ce52c87736ec5a39982f211d6a19f977f7fe6a8922af992b66b
  Stored in directory: C:\Users\bruce\AppData\Local\Temp\pip-ephem-wheel-cache-r2znb8a5\wheels\97\54\f5\d849319cdfa096e074df352654ee2e7c919da8951f090690c6
Successfully built my-project
Installing collected packages: werkzeug, my-project, markupsafe, jinja2, itsdangerous, flask, colorama, click, blinker
Successfully installed blinker-1.6.2 click-8.1.3 colorama-0.4.6 flask-2.3.2 itsdangerous-2.1.2 jinja2-3.1.2 markupsafe-2.1.3 my-project-0.1.0 werkzeug-2.3.6
Done!
PS C:\git\python-experiments\actors\my-project> python -c "import sys; print(sys.prefix)"
C:\Python
PS C:\git\python-experiments\actors\my-project> python -c "import flask"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'flask'
PS C:\git\python-experiments\actors\my-project> cd ..
PS C:\git\python-experiments\actors> python -c "import flask"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'flask'
PS C:\git\python-experiments\actors> cd .\my-project\
PS C:\git\python-experiments\actors\my-project> rye shell
error: environment variable not found
PS C:\git\python-experiments\actors\my-project>
```

### Version Info

rye 0.9.0
commit: 0.9.0 (4fe886c47 2023-06-21)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by BruceEckel** [comment]
Also note that when I run `python -c "import sys; print(sys.prefix)"`, it produces `C:\Python` which is where my pre-installed Python lives and is not the one that I would expect rye to be using.

**Comment by BruceEckel** [comment]
If I run activate, it succeeds:
```
PS C:\git\python-experiments\my-project> .\.venv\Scripts\activate
(.venv) PS C:\git\python-experiments\my-project> python -c "import flask"
(.venv) PS C:\git\python-experiments\my-project>
```

**Comment by mitsuhiko** [comment]
@BruceEckel can you run `where python`?

**Comment by BruceEckel** [comment]
In case this helps (outside of any venv):
```
PS C:\git\python-experiments> rye toolchain list
cpython@3.11.3 (C:\Users\bruce\.rye\py\cpython@3.11.3\install\python.exe)
```

**Comment by crashiam** [comment]
> PS C:\git\python-experiments\actors\my-project> python -c "import flask"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'flask'

@BruceEckel can you try this `rye run python -c "import flask"` ?

**Comment by mitsuhiko** [comment]
My hunch is that the `python` on the path is not from the `~/.rye/shims` folder but a different python. If `rye`'s Python does not come first, it requires the activation of the virtualenv.

**Comment by BruceEckel** [comment]
That sounds promising. Pursuing this hypothesis, here is my PATH:
```
PS C:\git\python-experiments> $env:path -split ";"
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.5.0_x64__8wekyb3d8bbwe
C:\Program Files\Common Files\Oracle\Java\javapath
C:\Python\Scripts\
C:\Python\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\PowerShell\7\
C:\Program Files\Git\cmd
C:\Program Files\dotnet\
C:\Users\bruce\.rye\shims
C:\Users\bruce\.cargo\bin
C:\Users\bruce\AppData\Local\Microsoft\WindowsApps
C:\Users\bruce\AppData\Local\GitHubDesktop\bin
C:\Users\bruce\AppData\Local\Programs\Microsoft VS Code\bin
```
This is a combination of the "System Variables" path, which is included first:

![image](https://github.com/mitsuhiko/rye/assets/1001900/38f82250-fdc2-4ad7-a7a3-7a8d1026664d)

And then the "User Variables" path is appended to that:

![image](https://github.com/mitsuhiko/rye/assets/1001900/cc281b24-42ec-44c9-86e5-80e66684d02a)

When you install Python from Python.org, it asks you whether you want to install it for everyone, or just this user. If you install it for everyone, as I did, then it puts the path information in the "System Variables" path. And since that comes before the "User Variables," it won't matter if you move the Rye shim to the top of your "User Variables" block, because the system-installed Python will still come first.

If this is indeed the case (and I need to test it), then the different possible solutions are:
1. Don't install a system Python, just use what Rye gives you. (Not sure if this works for scripts that don't use Rye, though).
2. If you install a system Python, install it "for this user only" so it goes into the "User Variables" path, then you can move the shims directory above the system Python directory.
3. If you install a system Python for all users, put the shims directory above the system Python director in the "System Variables" path.

I'll need to try some experiments to verify this.

**Comment by BruceEckel** [comment]
Result 1: If there is no system Python, rye doesn't provide one. If you move out of the directory of a rye project and type `python`, Microsoft will helpfully direct you to the "Python" entry in the Microsoft Store. Since I still need a system Python, I will try installing it from the store, rather than my usual Python.org.

**Comment by BruceEckel** [comment]
Result 2: The Microsoft Store experience was impressive; I didn't even have to restart my console window for it to be able to run Python. Because the Store installed a slightly newer version, we can see the difference:
```
PS C:\git> cd .\python-experiments\
PS C:\git\python-experiments> python --version
Python 3.11.4
PS C:\git\python-experiments> cd .\my-project\
PS C:\git\python-experiments\my-project> python --version
Python 3.11.3
PS C:\git\python-experiments\my-project>
```
The system Python is installed by the Store to `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps`.
Notice that this now appears after the shims directory:
```
PS C:\git\python-experiments\my-project> $env:path -split ";"
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.5.0_x64__8wekyb3d8bbwe
C:\Program Files\Common Files\Oracle\Java\javapath
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\PowerShell\7\
C:\Program Files\Git\cmd
C:\Program Files\dotnet\
C:\Users\bruce\.rye\shims
C:\Users\bruce\.cargo\bin
C:\Users\bruce\AppData\Local\Microsoft\WindowsApps
C:\Users\bruce\AppData\Local\GitHubDesktop\bin
C:\Users\bruce\AppData\Local\Programs\Microsoft VS Code\bin
```
My guess is that this *search path ordering* problem is going to come up regularly.

**Comment by BruceEckel** [comment]
Two thoughts; either:

- Rye somehow ensures that it's running a rye-installed python when it is in a rye project directory.
Or
- We add some version of the above explanations to the FAQ and hope people find it.

**Comment by mitsuhiko** [comment]
Rye can already provide an installation if outside of a managed path as an opt-in: https://rye-up.com/guide/shims/#global-shims

This definitely needs better docs. I also want to see how much work it is to offer automatically adding rye to the path during installation.

**Comment by BruceEckel** [comment]
I've been playing with it a lot and think I have a pretty good idea now of the installation pitfalls. Not sure the best way to explain it all yet, though.

One thing I've discovered is that the commands for detecting path locations are not producing expected results. In particular, looking for `python.exe` always finds the `.rye\shims` version of Python even when that isn't the one that's invoked when you are outside of a rye-managed directory. In the following, I'm starting in a non-rye-managed directory, which calls Python 3.11.4,
and then I move to a rye-managed directory which calls the Rye-installed version of Python which is 3.11.3:
```
PS C:\git\python-experiments\python_to_rust> which python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         0.0.0.0    C:\Users\bruce\.rye\shims\python.exe

PS C:\git\python-experiments\python_to_rust> (get-command python.exe).Path
C:\Users\bruce\.rye\shims\python.exe
PS C:\git\python-experiments\python_to_rust> python --version
Python 3.11.4
PS C:\git\python-experiments\python_to_rust> cd .\python_tree\
```
(now in a rye-managed directory)
```
PS C:\git\python-experiments\python_to_rust\python_tree> which python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         0.0.0.0    C:\Users\bruce\.rye\shims\python.exe

PS C:\git\python-experiments\python_to_rust\python_tree> (get-command python.exe).Path
C:\Users\bruce\.rye\shims\python.exe
PS C:\git\python-experiments\python_to_rust\python_tree> python --version
Python 3.11.3
PS C:\git\python-experiments\python_to_rust\python_tree>
```

**Comment by BruceEckel** [comment]
Also, even with the paths configured correctly I cannot run `rye shell`:
```
    Directory: C:\git\python-experiments\python_to_rust\python_tree

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           6/30/2023  7:51 PM                .venv
d----           6/30/2023  5:06 PM                src
-a---           6/30/2023  5:06 PM             16 .python-version
-a---           6/30/2023  7:51 PM            434 pyproject.toml
-a---           6/30/2023  5:06 PM             46 README.md
-a---           6/30/2023  7:52 PM            243 requirements-dev.lock
-a---           6/30/2023  7:52 PM            183 requirements.lock

PS C:\git\python-experiments\python_to_rust\python_tree> rye shell
error: environment variable not found
```

**Comment by mitsuhiko** [comment]
@BruceEckel `rye shell` does not properly work on windows annoyingly. I will need to fix this.

**Comment by mitsuhiko** [comment]
I'm closing this for now. The issue with the shell is already tracked in another issue.
