### ISSUE TITLE
Can't install a dependency that requires Cython to build

### ISSUE THREAD

**Issue by anna-hope** [mitsuhiko/rye#350]
### Steps to Reproduce

1. `rye init`
2. `rye pin 3.11`
3. `rye add pymrmre`
4. Edit `pyproject.toml` to add "Cython" to `build-system.requires`
5. `rye lock` or `rye sync`

### Expected Result

The package gets installed.

### Actual Result

```
Generating production lockfile: /Users/<me>/pymrmre-test/requirements.lock
    error: subprocess-exited-with-error

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [6 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/private/var/folders/b6/nm_w0grs5vx0_xq0tpsvft6h0000gn/T/pip-resolve-o_byvnx7/pymrmre_bb2d96c86213432cb8bc3034eaba94b0/setup.py", line 2, in <module>
            from Cython.Build import cythonize
        ModuleNotFoundError: No module named 'Cython'
        [end of output]
```

### Version Info

rye 0.9.0
commit: 0.9.0 (4fe886c47 2023-06-21)
platform: macos (aarch64)
self-python: cpython@3.11
symlink support: true

**Comment by bbqsrc** [comment]
It seems that this is specifically a limitation of hatchling: https://github.com/pypa/hatch/issues/279

**Comment by bluss** [comment]
Seems like it is unrelated to rye issue, because this reproduces with python3.11 (from Rye) and python3.10 (from Ubuntu)

```
python +3.11 -m venv ryes/cy3
. ryes/cy3/bin/activate
python -m pip install "pymrmre==1.0.7"
Collecting pymrmre==1.0.7
  Downloading pymrmre-1.0.7.tar.gz (18.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 11.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jk3p4mbt/pymrmre_2e0fe4eff318460d84de1ee23f7c54d7/setup.py", line 2, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```


It seems like pymrmre does not declare its own build dependencies in a way that's compatible with newer python and pip. It does specify `setup_requires` but pip does not use that (anymore?)
