### ISSUE TITLE
polyglot's dependency is not installing

### ISSUE THREAD

**Issue by chatblanc-ciel** [mitsuhiko/rye#362]
### Steps to Reproduce

1. `rye init test ` & `cd test`
2. `rye add polyglot` is sucsses.
3. But polyglot's dependency is not installing -> this libraly is not working.

https://github.com/aboSamoor/polyglot

I think it is cause repo has only `requirements.txt` & `setup.py`.

### Expected Result

sucsses installing dependencies.

### Actual Result

fail installing dependencies.

### Version Info

rye 0.10.0
commit: unknown (87d392d74 2023-06-23)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: false

---
windows 11

### Stacktrace

not crash

**Comment by cnpryer** [comment]
Im not familiar with that package but are you running into this by any chance?

https://github.com/aboSamoor/polyglot/issues/261

I can check when I'm at my computer, but that project doesn't seem maintained.

**Comment by chatblanc-ciel** [comment]
@cnpryer 

Thank you for reply.

> I can check when I'm at my computer, but that project doesn't seem maintained.

That is certainly true. But I can using this library via `pip tool`, so I think `Rye` cannot use package via `requirements.txt & setup.py`.
Is it right?

**Comment by cnpryer** [comment]
Could you provide more information about what you're doing? Is this what you're seeing?
```sh
@cnpryer ➜ /workspaces/sandbox/x/test $ . ./.venv/bin/activate
(.venv) @cnpryer ➜ /workspaces/sandbox/x/test $ python
Cannot read termcap database;
using dumb terminal settings.
Python 3.11.1 (main, Jan 16 2023, 22:41:20) [Clang 15.0.7 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polyglot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/sandbox/x/test/.venv/lib/python3.11/site-packages/polyglot/__init__.py", line 11, in <module>
    from six.moves import copyreg
ModuleNotFoundError: No module named 'six'

(.venv) @cnpryer ➜ /workspaces/sandbox/x/test $ rye --version
rye 0.12.0
commit: 0.11.0+1 (d9b040b1c 2023-07-18)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by chatblanc-ciel** [comment]
@cnpryer 
Nearly, but same. Please see below.
(Directory name masked because its name is include private infomations, sorry.)

```sh
~/Downloads> rye init rye_test
success: Initialized project in C:\Downloads\rye_test
  Run `rye sync` to get started
~/Downloads> cd rye_test                                                                        
~/Downloads/rye_test> rye sync                                                                  
Initializing new virtualenv in C:\Downloads\rye_test\.venv
Python version: cpython@3.11.3
Generating production lockfile: C:\Downloads\rye_test\requirements.lock
Generating dev lockfile: C:\Downloads\rye_test\requirements-dev.lock
Installing dependencies
Looking in indexes: https://pypi.org/simple/
Obtaining file:///. (from -r C:\Local\Temp\tmpn036jy1f (line 1))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: rye-test
  Building editable for rye-test (pyproject.toml) ... done
  Created wheel for rye-test: filename=rye_test-0.1.0-py3-none-any.whl size=1066 sha256=497323003253ea4b3cf298d1bce056a614bd12f4517955cfd8c0909f27ff3816
  Stored in directory: C:\Local\Temp\pip-ephem-wheel-cache-2mx6lnz1\wheels\97\54\f5\d849319cdfa096e074df352654ee2e7c919da8951f090690c6
Successfully built rye-test
Installing collected packages: rye-test
Successfully installed rye-test-0.1.0
Done!
Added polyglot>=16.7.4 as regular dependency
~/Downloads/rye_test> rye sync                                                                  
Reusing already existing virtualenv
Generating production lockfile: C:\Downloads\rye_test\requirements.lock
Generating dev lockfile: C:\Downloads\rye_test\requirements-dev.lock
Installing dependencies
Found existing installation: rye-test 0.1.0
Uninstalling rye-test-0.1.0:
  Successfully uninstalled rye-test-0.1.0
Obtaining file:///. (from -r C:\Local\Temp\tmppnjx3up9 (line 1))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting polyglot==16.7.4 (from -r C:\Local\Temp\tmppnjx3up9 (line 2))
  Using cached polyglot-16.7.4-py2.py3-none-any.whl
Building wheels for collected packages: rye-test
  Building editable for rye-test (pyproject.toml) ... done
  Created wheel for rye-test: filename=rye_test-0.1.0-py3-none-any.whl size=1089 sha256=7a540f4dc39c006be828be3a3a8e724d8106831013f1cba97dedef58f54610e5
  Stored in directory: C:\Local\Temp\pip-ephem-wheel-cache-_c7kv6ca\wheels\97\54\f5\d849319cdfa096e074df352654ee2e7c919da8951f090690c6
Successfully built rye-test
Installing collected packages: polyglot, rye-test
Successfully installed polyglot-16.7.4 rye-test-0.1.0
Done!
~/Downloads/rye_test> rye run python                                                           
Python 3.11.3 (main, May  7 2023, 18:40:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import polyglot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Downloads\rye_test\.venv\Lib\site-packages\polyglot\__init__.py", line 11, in <module>
    from six.moves import copyreg
ModuleNotFoundError: No module named 'six'
>>> exit()
~/Downloads/rye_test> rye --version                                                             07/19/2023 03:32:25 午後
rye 0.10.0
commit: unknown (87d392d74 2023-06-23)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: false
```
