### ISSUE TITLE
rye sync fails when directory path contains space character

### ISSUE THREAD

**Issue by sbarrios93** [mitsuhiko/rye#37]
When starting a new project

```bash
➜ rye init
success: Initialized project in /Users/seba/Dropbox/MBA/Spring 2023/pm/hw6/.
```

but sync fails because of the space character in the directory path.

```bash
➜ rye sync
Initializing new virtualenv in /Users/seba/Dropbox/MBA/Spring 2023/pm/hw6/.venv
Python version: cpython@3.11.1
Generating production lockfile: /Users/seba/Dropbox/MBA/Spring 2023/pm/hw6/requirements.lock
Traceback (most recent call last):
  File "/Users/seba/.rye/self/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/piptools/scripts/compile.py", line 517, in cli
    constraints.extend(
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/piptools/_compat/pip_compat.py", line 36, in parse_requirements
    yield install_req_from_parsed_requirement(parsed_req, isolated=isolated)
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 459, in install_req_from_parsed_requirement
    req = install_req_from_editable(
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 214, in install_req_from_editable
    parts = parse_req_from_editable(editable_req)
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 183, in parse_req_from_editable
    name, url, extras_override = parse_editable(editable_req)
  File "/Users/seba/.rye/self/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 100, in parse_editable
    raise InstallationError(
pip._internal.exceptions.InstallationError: /Users/seba/Dropbox/MBA/Spring is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
Error: could not write production lockfile for project

Caused by:
    failed to generate lockfile
```

**Comment by sbarrios93** [comment]
no lock files

```bash
$ l

Permissions Size User Date Modified Name
drwxr-xr-x     - seba 25 Apr 12:08  .venv
.rw-r--r--    93 seba 25 Apr 12:08  .gitignore
.rw-r--r--   358 seba 25 Apr 12:08  pyproject.toml
.rw-r--r--    54 seba 25 Apr 12:08  README.md
```
