### ISSUE TITLE
[Question] How to install dependencies by different sources

### ISSUE THREAD

**Issue by QIN2DIM** [mitsuhiko/rye#423]
## Expected

Download `torch` and `torchvision` through special Pytorch(CUDA) source, other dependencies download from PyPI.

In addition, I tried the same operation at `poetry`, but it did not work.

https://pytorch.org/get-started/locally/
![image](https://github.com/mitsuhiko/rye/assets/62018067/61cbcef7-0f91-46df-b630-2ca374daeed1)

## Other methods

Execution in two times can perfectly solve my needs.

```bash
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
```

```bash
pip install -U loguru fire numpy ...
```

## Inspect

```markdown
$ rye --version
rye 0.11.0
commit: 0.11.0 (f6f63d6c1 2023-07-18)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true

```

## ~/.rye/config.toml

```toml
[proxy]
https = "http://127.0.0.1:7890"  # it's works
```

## Pyproject.toml

(Related configuration)
https://rye-up.com/guide/pyproject/#projectdependencies
https://rye-up.com/guide/sources/#index-types
```toml
[project]
dependencies = [
    "torchvision>=0.15.2+cu118",
    "torch>=2.0.1+cu118",
    "loguru",
    "fire",
    "PyYAML",
    "numpy>=1.24.1",
    "Pillow>=9.3.0",
    "opencv-python>=4.8.0.76",
    "onnx>=1.14.0",
    "hcaptcha_challenger>=0.6.2-post1",
    "APScheduler>=3.10.3"
]
requires-python = ">= 3.10"

[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
type = "index"
```

## logs

```log
$ rye sync
Initializing new virtualenv in E:\_GithubProjects\Forks\hcaptcha-model-factory\.venv
Python version: cpython@3.10.11
Generating production lockfile: E:\_GithubProjects\Forks\hcaptcha-model-factory\requirements.lock
    error: subprocess-exited-with-error

    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [22 lines of output]
        Traceback (most recent call last):
          File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
            whl_basename = backend.build_wheel(metadata_directory, config_settings)
          File "C:\Users\yaoqinse\AppData\Local\Temp\pip-build-env-g4nisgv4\overlay\Lib\site-packages\hatchling\build.py", line 56, in build_wheel
            return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
          File "C:\Users\yaoqinse\AppData\Local\Temp\pip-build-env-g4nisgv4\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 93, in build
            self.metadata.validate_fields()
          File "C:\Users\yaoqinse\AppData\Local\Temp\pip-build-env-g4nisgv4\overlay\Lib\site-packages\hatchling\metadata\core.py", line 244, in validate_fields
            self.core.validate_fields()
          File "C:\Users\yaoqinse\AppData\Local\Temp\pip-build-env-g4nisgv4\overlay\Lib\site-packages\hatchling\metadata\core.py", line 1325, in validate_fields
            getattr(self, attribute)
          File "C:\Users\yaoqinse\AppData\Local\Temp\pip-build-env-g4nisgv4\overlay\Lib\site-packages\hatchling\metadata\core.py", line 1200, in dependencies
            self._dependencies = list(self.dependencies_complex)
          File "C:\Users\yaoqinse\AppData\Local\Temp\pip-build-env-g4nisgv4\overlay\Lib\site-packages\hatchling\metadata\core.py", line 1179, in dependencies_complex
            raise ValueError(message) from None
        ValueError: Dependency #1 of field `project.dependencies` is invalid: Local version label can only be used with `==` or `!=` operators
            torchvision>=0.15.2+cu118
                       ~~~~~~~~^
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\operations\build\metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\utils\misc.py", line 718, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 311, in _call_hook       
    self._subprocess_runner(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\utils\subprocess.py", line 252, in runner
    call_subprocess(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\utils\subprocess.py", line 224, in call_subprocess     
    raise error
pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yaoqinse\.rye\py\cpython@3.10.11\install\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yaoqinse\.rye\py\cpython@3.10.11\install\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\Scripts\pip-compile.exe\__main__.py", line 7, in <module>
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\piptools\scripts\compile.py", line 592, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\piptools\resolver.py", line 593, in resolve
    is_resolved = self._do_resolve(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\piptools\resolver.py", line 625, in _do_resolve
    resolver.resolve(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 318, in __init__
    super().__init__(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 328, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\operations\prepare.py", line 709, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\distributions\sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\req\req_install.py", line 562, in prepare_metadata     
    self.metadata_directory = generate_metadata(
  File "C:\Users\yaoqinse\.rye\pip-tools\cpython@3.10\lib\site-packages\pip\_internal\operations\build\metadata.py", line 37, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
error: could not write production lockfile for project

Caused by:
    failed to generate lockfile

```

**Comment by Prgckwb** [comment]
In your project's pyproject.toml, use _tool.rye.sources_ instead of _sources_ .

https://rye-up.com/guide/sources/#adding-a-source

[[sources]] → [[tool.rye.sources]]

**Comment by QIN2DIM** [comment]
@Prgckwb Thank you for reminding me that I have modified the reference configuration in Issue.

But unfortunately, what I used to use when I actually ran was `[tool.rye.sources]` ``

The reference configuration I provided is that I wrote wrong when editing questions.

🐧

**Comment by QIN2DIM** [comment]
@Prgckwb Thanks for reminding me, I realize what the problem is.

## Init

```bash
rye init
rye pin 3.10
rye sync
```

## Expected

```python
import torch

print(torch.__version__)
# 2.0.1+cu118

print(torch.cuda_version)
# 11.8
```



## pyproject.toml

```toml
[project]
dependencies = [
    "torchvision",
    "torch",
    "loguru",
]
requires-python = ">= 3.10"

[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
type = "index"

```

## logs

```log
$ rye sync
Initializing new virtualenv in E:\_GithubProjects\scripts\draft\poetry-demo\.venv
Python version: cpython@3.10.11
Generating production lockfile: E:\_GithubProjects\scripts\draft\poetry-demo\requirements.lock
Generating dev lockfile: E:\_GithubProjects\scripts\draft\poetry-demo\requirements-dev.lock
Installing dependencies
Looking in indexes: https://download.pytorch.org/whl/cu118, https://pypi.org/simple/, https://pypi.org/simple/
Obtaining file:///. (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 4))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting certifi==2023.7.22 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 1))
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting charset-normalizer==3.2.0 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 2))
  Using cached charset_normalizer-3.2.0-cp310-cp310-win_amd64.whl (96 kB)
Collecting colorama==0.4.6 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 3))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting filelock==3.12.2 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 5))
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting idna==3.4 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 6))
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting jinja2==3.1.2 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 7))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting loguru==0.7.0 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 8))
  Using cached loguru-0.7.0-py3-none-any.whl (59 kB)
Collecting markupsafe==2.1.3 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 9))
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting mpmath==1.3.0 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 10))
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting networkx==3.1 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 11))
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting numpy==1.25.2 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 12))
  Using cached numpy-1.25.2-cp310-cp310-win_amd64.whl (15.6 MB)
Collecting pillow==10.0.0 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 13))
  Using cached Pillow-10.0.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting requests==2.31.0 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 14))
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting sympy==1.12 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 15))
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting torch==2.0.1+cu118 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 16))
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting torchvision==0.15.2+cu118 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 17))
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting typing-extensions==4.7.1 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 18))
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting urllib3==2.0.4 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 19))
  Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Collecting win32-setctime==1.1.0 (from -r C:\Users\yaoqinse\AppData\Local\Temp\tmplhr0dhbo (line 20))
  Using cached win32_setctime-1.1.0-py3-none-any.whl (3.6 kB)
Building wheels for collected packages: poetry-demo
  Building editable for poetry-demo (pyproject.toml) ... done
  Created wheel for poetry-demo: filename=poetry_demo-0.1.0-py3-none-any.whl size=1076 sha256=2f7b77d1f85c7fe991898cac9bd854f07b96d8b880e5a55b000c69ede1375ff4
  Stored in directory: C:\Users\yaoqinse\AppData\Local\Temp\pip-ephem-wheel-cache-qkig511i\wheels\78\12\b9\db4c72ae1aebdfd866f484b59eb7b39f206b7d7d1080ae28b1
Successfully built poetry-demo
Installing collected packages: mpmath, win32-setctime, urllib3, typing-extensions, torchvision, torch, sympy, requests, poetry-demo, pillow, numpy, networkx, markupsafe, loguru, jinja2, idna, filelock, colorama, charset-normalizer, certifi
Successfully installed certifi-2023.7.22 charset-normalizer-3.2.0 colorama-0.4.6 filelock-3.12.2 idna-3.4 jinja2-3.1.2 loguru-0.7.0 markupsaf
e-2.1.3 mpmath-1.3.0 networkx-3.1 numpy-1.25.2 pillow-10.0.0 poetry-demo-0.1.0 requests-2.31.0 sympy-1.12 torch-2.0.1+cu118 torchvision-0.15.2+cu118 typing-extensions-4.7.1 urllib3-2.0.4 win32-setctime-1.1.0
Done!

```
