### ISSUE TITLE
`rye sync` fails to install build dependency (hatchling)

### ISSUE THREAD

**Issue by mattgiles** [mitsuhiko/rye#424]
### Steps to Reproduce

Not sure how to reliably reproduce. I'm working on an existing project, but on a new mac mini (m2).

I note that:
- on first (ever on this computer) `sync`, I got a complaint about pip not being found. Which I resolved by aliasing `pip` to `pip3` in my shell profile.
- on second `sync`, I got a new complaint about `http://pypi.org` not being trusted, and resolved by adding the trusted host explicitly to a new `pip.conf` file, as well as by running `pip3 config set global.index-url https://pypi.org` to try to force `https`.
- on third `sync` I ran into the issue described here and don't know how to best resolve. I also don't know if the earlier issues listed above are symptoms of some other problem that I'm running away from by e.g. customizing my shell profile or pip config etc. `rye sync` is still using `http`.

### Expected Result

I expect that rye's build dependencies install (if needed) successfully.

### Actual Result

Output looks like:

```
% rye sync
Reusing already existing virtualenv
Generating production lockfile: /Users/matt/dev/project/requirements.lock
    error: subprocess-exited-with-error

    × pip subprocess to install build dependencies did not run successfully.
    │ exit code: 1
    ╰─> [3 lines of output]
        Looking in indexes: http://pypi.org/simple/
        ERROR: Could not find a version that satisfies the requirement hatchling (from versions: none)
        ERROR: No matching distribution found for hatchling
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Version Info

```
% rye --version
rye 0.11.0
commit: 0.11.0 (f6f63d6c1 2023-07-18)
platform: macos (aarch64)
self-python: cpython@3.11
symlink support: true
```

### Stacktrace

The full stacktrace looks like:

```
Traceback (most recent call last):
  File "/Users/matt/.rye/pip-tools/cpython@3.10/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/piptools/scripts/compile.py", line 592, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/piptools/resolver.py", line 593, in resolve
    is_resolved = self._do_resolve(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/piptools/resolver.py", line 625, in _do_resolve
    resolver.resolve(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 185, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in __init__
    super().__init__(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 328, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 709, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._prepare_build_backend(finder)
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 70, in _prepare_build_backend
    self.req.build_env.install_requirements(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/build_env.py", line 217, in install_requirements
    self._install_requirements(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/build_env.py", line 275, in _install_requirements
    call_subprocess(
  File "/Users/matt/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: pip subprocess to install build dependencies exited with 1
```

**Comment by mattgiles** [comment]
Solved.

The rye-installed config at `~/.rye/config.toml` contains these values:

```
[[sources]]
name = "default"
url = "http://pypi.org/simple/"
```

Changing to `https` fixed the issue.
