### ISSUE TITLE
Hatchling 1.19 breaks `rye sync`

### ISSUE THREAD

**Issue by indigoviolet** [mitsuhiko/rye#515]
### Steps to Reproduce

See

https://github.com/pypa/hatch/issues/1113

```
❯ rye sync --no-lock
Reusing already existing virtualenv
Installing dependencies
Looking in indexes: https://pypi.org/simple/, https://pypi.org/simple/
Obtaining file:///. (from -r /tmp/tmpo2k2iiit (line 1))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "/tmp/.tmpy1qEr0/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 167, in prepare_metadata_for_build_editable
          hook = backend.prepare_metadata_for_build_editable
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'
```

### Expected Result

`rye sync` should succeed

### Actual Result

```
❯ rye sync --no-lock
Reusing already existing virtualenv
Installing dependencies
Looking in indexes: https://pypi.org/simple/, https://pypi.org/simple/
Obtaining file:///. (from -r /tmp/tmpo2k2iiit (line 1))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "/tmp/.tmpy1qEr0/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 167, in prepare_metadata_for_build_editable
          hook = backend.prepare_metadata_for_build_editable
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'
```

### Version Info

❯ rye --version
rye 0.15.2
commit: 0.15.2 (2023-10-04)
platform: macos (aarch64)
self-python: cpython@3.11
symlink support: true

**Comment by ofek** [comment]
Please show the full error.

**Comment by ofek** [comment]
The issue is that your project was relying on the buggy fallback that tried to find every Python file that did not look like a test file. I assume your project name does not match the directory, in which case you have to explicitly define an option indicating what to include in the wheel.

**Comment by indigoviolet** [comment]
Thanks @ofek! The linked issue on the Hatch tracker does explain that and I will apply the fix, mostly I'm posting here as a pointer for people who use rye's defaults and encounter this.

**Comment by indigoviolet** [comment]
I'm also not sure if this error is only due to the project name, or also caused if there is a workspace involved, and what the right fix is in the latter case.

**Comment by ricka** [comment]
Based on [this comment](https://github.com/pypa/hatch/issues/1113#issuecomment-1851120906), should rye consider pinning hatch version for reproducibility?

**Comment by majidaldo** [comment]
defaults would need to be considered on `rye init`.

**Comment by NikOcaml** [comment]
Previously, out of the blue, I got the following error:

```
> rye init -p 3.10.13 -r requirements.txt --dev-requirements dev-requirements.txt --no-readme
...
> rye sync

Downloading cpython@3.10.13
Checking checksum
success: Downloaded cpython@3.10.13
Initializing new virtualenv in /Users/NK/HUTA/huta_frontend/.venv
Python version: cpython@3.10.13
Generating production lockfile: /Users/NK/HUTA/huta_frontend/requirements.lock
Creating virtualenv for pip-tools
    error: subprocess-exited-with-error
    
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [33 lines of output]
        Traceback (most recent call last):
          File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
            whl_basename = backend.build_wheel(metadata_directory, config_settings)
          File "/private/var/folders/yx/rr0khy_54x1cc01m3y0scyqr0000gp/T/pip-build-env-d_1vwj4p/overlay/lib/python3.10/site-packages/hatchling/build.py", line 58, in build_wheel
            return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
          File "/private/var/folders/yx/rr0khy_54x1cc01m3y0scyqr0000gp/T/pip-build-env-d_1vwj4p/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
            artifact = version_api[version](directory, **build_data)
          File "/private/var/folders/yx/rr0khy_54x1cc01m3y0scyqr0000gp/T/pip-build-env-d_1vwj4p/overlay/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 412, in build_standard
            for included_file in self.recurse_included_files():
          File "/private/var/folders/yx/rr0khy_54x1cc01m3y0scyqr0000gp/T/pip-build-env-d_1vwj4p/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 176, in recurse_included_files
            yield from self.recurse_selected_project_files()
          File "/private/var/folders/yx/rr0khy_54x1cc01m3y0scyqr0000gp/T/pip-build-env-d_1vwj4p/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 180, in recurse_selected_project_files
            if self.config.only_include:
          File "/private/var/folders/yx/rr0khy_54x1cc01m3y0scyqr0000gp/T/pip-build-env-d_1vwj4p/overlay/lib/python3.10/site-packages/hatchling/builders/config.py", line 781, in only_include
            only_include = only_include_config.get('only-include', self.default_only_include()) or self.packages
          File "/private/var/folders/yx/rr0khy_54x1cc01m3y0scyqr0000gp/T/pip-build-env-d_1vwj4p/overlay/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 231, in default_only_include
            return self.default_file_selection_options.only_include
          File "/Users/NK/.rye/py/cpython@3.10.13/install/lib/python3.10/functools.py", line 981, in __get__
            val = self.func(instance)
          File "/private/var/folders/yx/rr0khy_54x1cc01m3y0scyqr0000gp/T/pip-build-env-d_1vwj4p/overlay/lib/python3.10/site-packages/hatchling/builders/wheel.py", line 219, in default_file_selection_options
            raise ValueError(message)
        ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection
        
        At least one file selection option must be defined in the `tool.hatch.build.targets.wheel` table, see: https://hatch.pypa.io/latest/config/build/
        
        As an example, if you intend to ship a directory named `foo` that resides within a `src` directory located at the root of your project, you can define the following:
        
        [tool.hatch.build.targets.wheel]
        packages = ["src/foo"]
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 772, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/NK/.rye/pip-tools/cpython@3.10/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/piptools/scripts/compile.py", line 592, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/piptools/resolver.py", line 593, in resolve
    is_resolved = self._do_resolve(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/piptools/resolver.py", line 625, in _do_resolve
    resolver.resolve(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 513, in collect_root_requirements
    reqs = list(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 474, in _make_requirements_from_install_req
    cand = self._make_candidate_from_link(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 190, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in __init__
    super().__init__(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 328, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 696, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 577, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/Users/NK/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
error: could not write production lockfile for project
```

After adding the above mentioned workaround
```
[build-system]
requires = ["hatchling<=1.18.0"]
build-backend = "hatchling.build"
```
The error ceases to exist.  Rye 0.15.2.

**Comment by ofek** [comment]
Did you happen to read the error?

**Comment by mitsuhiko** [comment]
I'm inclined to just pin hatchling down to the previous version for now. Even rye's own docs no longer build and I'm not even sure how to fix it without downgrading as there I'm not even shipping any code (just using it as a dummy workspace for mkdocs).

**Comment by ofek** [comment]
What is not working exactly?

**Comment by mitsuhiko** [comment]
For a project without a package, hatch worked in 1.18 fine, in 1.19 you kinda need to add a dummy (see `pyproject.toml` in this repo)

```toml
[tool.hatch.build.targets.wheel]
packages = ["dummy"]
```

**Comment by mitsuhiko** [comment]
For anyone who runs into this on an existing project, add this to your `pyproject.toml`:

```toml
[tool.hatch.build.targets.wheel]
packages = ["src/YOUR_PACKAGE_NAME"]
```

**Comment by ifplusor** [comment]
> For a project without a package, hatch worked in 1.18 fine, in 1.19 you kinda need to add a dummy (see `pyproject.toml` in this repo)
> 
> ```toml
> [tool.hatch.build.targets.wheel]
> packages = ["dummy"]
> ```

Maybe using `tool.hatch.build.targets.bypass-selection` is better.

FYI https://github.com/pypa/hatch/pull/1135

**Comment by ofek** [comment]
Yes, that would be the correct approach!
