### ISSUE TITLE
Invalid script entry point - A callable suffix is required.

### ISSUE THREAD

**Issue by yokomotod** [mitsuhiko/rye#526]
### Steps to Reproduce

Now rye seems to generate invalid pyproject.toml and failed to sync, if project name includes `-`.
```
$ rye init foo-bar
$ cd foo-bar
$ rye sync
...
ERROR: For req: foo-bar==0.1.0. Invalid script entry point: <ExportEntry hello = foo:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
...
```

### Expected Result

Successfully installed

### Actual Result

```
ERROR: For req: foo-bar==0.1.0. Invalid script entry point: <ExportEntry hello = foo:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
Traceback (most recent call last):
  File "/Users/xxxxxxxx/.rye/pip-tools/cpython@3.12/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/xxxxxxxx/.rye/pip-tools/cpython@3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxxxx/.rye/pip-tools/cpython@3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/xxxxxxxx/.rye/pip-tools/cpython@3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxxxx/.rye/pip-tools/cpython@3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxxxx/.rye/pip-tools/cpython@3.12/lib/python3.12/site-packages/piptools/scripts/sync.py", line 174, in cli
    sync.sync(
  File "/Users/xxxxxxxx/.rye/pip-tools/cpython@3.12/lib/python3.12/site-packages/piptools/sync.py", line 244, in sync
    run(  # nosec
  File "/Users/xxxxxxxx/.rye/py/cpython@3.12.0/install/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/xxxxxxxx/workspace/sandbox/foo-bar/.venv/bin/python', '-m', 'pip', 'install', '-r', '/var/folders/wz/_p5pqjnx3glfrth9f3g658280000gr/T/tmpjxapjcos', '--index-url', 'https://pypi.org/simple/', '--python=/Users/xxxxxxxx/workspace/sandbox/foo-bar/.venv/bin/python', '--no-deps']' returned non-zero exit status 1.
error: Installation of dependencies failed
```

### Version Info

rye 0.16.0
commit: 0.16.0 (c003223d5 2023-12-16)
platform: macos (aarch64)
self-python: cpython@3.11
symlink support: true

**Comment by usernein** [comment]
Same happening for me when the project name contains `_`

**Comment by zhuang1234** [comment]
this need wait [pip-tools](https://github.com/jazzband/pip-tools) to fixed
