### ISSUE TITLE
Can't run `rye sync` successfully

### ISSUE THREAD

**Issue by Jordan-Haidee** [mitsuhiko/rye#528]
### Steps to Reproduce

1. `rye init rye-start`
2. `rye pin 3.10`
3. `rye sync`
4. `rye add 'flask>=2.0'`
5. `rye sync`

### Expected Result

`rye sync` runs, and needed denpendencies can be installed successfully.

### Actual Result

✗  rye sync
Reusing already existing virtualenv
Generating production lockfile: D:\py-projects\rye-start\requirements.lock
Generating dev lockfile: D:\py-projects\rye-start\requirements-dev.lock
Installing dependencies
Looking in indexes: https://pypi.org/simple/
Obtaining file:///. (from -r C:\Users\dell\AppData\Local\Temp\tmp8vwxq0g8 (line 4))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting blinker==1.7.0 (from -r C:\Users\dell\AppData\Local\Temp\tmp8vwxq0g8 (line 1))
  Using cached blinker-1.7.0-py3-none-any.whl (13 kB)
Collecting click==8.1.7 (from -r C:\Users\dell\AppData\Local\Temp\tmp8vwxq0g8 (line 2))
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting colorama==0.4.6 (from -r C:\Users\dell\AppData\Local\Temp\tmp8vwxq0g8 (line 3))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting flask==3.0.0 (from -r C:\Users\dell\AppData\Local\Temp\tmp8vwxq0g8 (line 5))
  Using cached flask-3.0.0-py3-none-any.whl (99 kB)
Collecting itsdangerous==2.1.2 (from -r C:\Users\dell\AppData\Local\Temp\tmp8vwxq0g8 (line 6))
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting jinja2==3.1.2 (from -r C:\Users\dell\AppData\Local\Temp\tmp8vwxq0g8 (line 7))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting markupsafe==2.1.3 (from -r C:\Users\dell\AppData\Local\Temp\tmp8vwxq0g8 (line 8))
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Building wheels for collected packages: rye-start
  Building editable for rye-start (pyproject.toml) ... done
  Created wheel for rye-start: filename=rye_start-0.1.0-py3-none-any.whl size=1306 sha256=96acfa9fe5d63b172d3f4e2af5c7f5d8eaaec131a250371fc69eb852be6088f1
  Stored in directory: C:\Users\dell\AppData\Local\Temp\pip-ephem-wheel-cache-wislwd7l\wheels\78\12\b9\db4c72ae1aebdfd866f484b59eb7b39f206b7d7d1080ae28b1
Successfully built rye-start
Installing collected packages: rye-start, markupsafe, jinja2, itsdangerous, flask, colorama, click, blinker
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_vendor\pkg_resources\__init__.py", line 2935, in get_entry_map
    ep_map = self._ep_map
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_vendor\pkg_resources\__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\commands\install.py", line 449, in run
    installed = install_given_reqs(
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\req\__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\req\req_install.py", line 800, in install
    install_wheel(
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\operations\install\wheel.py", line 731, in install_wheel
    _install_wheel(
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\operations\install\wheel.py", line 565, in _install_wheel
    console, gui = get_entrypoints(distribution)
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\operations\install\wheel.py", line 121, in get_entrypoints
    for entry_point in dist.iter_entry_points():
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_internal\metadata\pkg_resources.py", line 186, in iter_entry_points
    for group, entries in self._dist.get_entry_map().items():
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_vendor\pkg_resources\__init__.py", line 2937, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_vendor\pkg_resources\__init__.py", line 2609, in parse_map
    maps[group] = cls.parse_group(group, lines, dist)
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_vendor\pkg_resources\__init__.py", line 2587, in parse_group
    ep = cls.parse(line, dist)
  File "C:\Users\dell\AppData\Local\Temp\.tmpP5OZ6I\pip\_vendor\pkg_resources\__init__.py", line 2565, in parse
    raise ValueError(msg, src)
ValueError: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'hello = rye-start:hello')
Traceback (most recent call last):
  File "C:\Users\dell\.rye\py\cpython@3.10.13\install\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dell\.rye\py\cpython@3.10.13\install\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dell\.rye\pip-tools\cpython@3.10\Scripts\pip-sync.exe\__main__.py", line 7, in <module>
  File "C:\Users\dell\.rye\pip-tools\cpython@3.10\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dell\.rye\pip-tools\cpython@3.10\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\dell\.rye\pip-tools\cpython@3.10\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dell\.rye\pip-tools\cpython@3.10\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\dell\.rye\pip-tools\cpython@3.10\lib\site-packages\piptools\scripts\sync.py", line 174, in cli
    sync.sync(
  File "C:\Users\dell\.rye\pip-tools\cpython@3.10\lib\site-packages\piptools\sync.py", line 244, in sync
    run(  # nosec
  File "C:\Users\dell\.rye\py\cpython@3.10.13\install\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\py-projects\\rye-start\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', '-r', 'C:\\Users\\dell\\AppData\\Local\\Temp\\tmp8vwxq0g8', '--index-url', 'https://pypi.org/simple/', '--python=D:\\py-projects\\rye-start\\.venv\\Scripts\\python.exe', '--no-deps']' returned non-zero exit status 2.
error: Installation of dependencies failed

### Version Info

rye 0.16.0
commit: 0.16.0 (c003223d5 2023-12-16)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true

### Stacktrace

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: BaseThreadInitThunk
  13: RtlUserThreadStart

**Comment by elfnor** [comment]
Me too
very similar
on first run of rye sync

```
$ rye --version
rye 0.16.0
commit: 0.16.0 (c003223d5 2023-12-16)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by elfnor** [comment]
Maybe a problem with characters in project name
for me this works
```
rye init newtest
cd newtest
rye sync
```
but not
```
rye init new_test
cd new_test
rye sync
```

related to #526 ?

**Comment by Jordan-Haidee** [comment]
Yeah, they are same.

**Comment by ischaojie** [comment]
Maybe related PR: https://github.com/mitsuhiko/rye/pull/519
