### ISSUE TITLE
AttributeError: 'list' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by lijc210** [mitsuhiko/rye#546]
### Steps to Reproduce

rye add requests

### Expected Result

Adds a Python package to this project

### Actual Result

ubuntu@VM-16-17-ubuntu:~/chatgpt-on-wechat$ rye add requests
error: failed to resolve package requests
Traceback (most recent call last):
  File "<string>", line 24, in <module>
  File "<string>", line 24, in <listcomp>
  File "<string>", line 22, in <genexpr>
  File "/home/ubuntu/.rye/self/lib/python3.11/site-packages/unearth/finder.py", line 294, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked, hashes)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.rye/self/lib/python3.11/site-packages/unearth/finder.py", line 263, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.rye/self/lib/python3.11/site-packages/unearth/finder.py", line 244, in find_one_source
    link = self._build_index_page_link(source["url"], package_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.rye/self/lib/python3.11/site-packages/unearth/finder.py", line 173, in _build_index_page_link
    urljoin(index_url.rstrip("/") + "/", canonicalize_name(package_name) + "/")
            ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'rstrip'

### Version Info

rye 0.18.0
commit: 0.18.0 (103afa59a 2024-01-20)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by AtomsForPeace** [comment]
I'm got the same issue

**Comment by AtomsForPeace** [comment]
Workaround is to add the dependencies directly to the pyproject.toml file for now.
eg.
dependencies = [
    "flask==3.0.1"
]

**Comment by mitsuhiko** [comment]
Sorry for this. This was a regression in the latest release. I am pushing out 0.19 which has a fix for this in.
