### ISSUE TITLE
add requirements check requires_python version whether support or not?

### ISSUE THREAD

**Issue by CharlesChen0823** [mitsuhiko/rye#63]
execute `rye add jinja`，and `rye sync`， then it will raise exception, current requirement not supported current python version.
Should check unearth output link.requires_python or not ?

**Comment by mitsuhiko** [comment]
I'm surprised you get a requirement error because I'm pretty sure that the old Jinja engine does not have enough metadata to carry information about which Python version it requires. Can you provide the output that you see?

**Comment by CharlesChen0823** [comment]
below is the test for django
```
ubuntu@VM-16-15-ubuntu:~/program/python/ryetest$ rye add django
Added django~=4.2
ubuntu@VM-16-15-ubuntu:~/program/python/ryetest$ rye sync
Reusing already existing virtualenv
Generating production lockfile: /home/ubuntu/program/python/ryetest/requirements.lock
Generating dev lockfile: /home/ubuntu/program/python/ryetest/requirements-dev.lock
Installing dependencies
Found existing installation: ryetest 0.1.0
Uninstalling ryetest-0.1.0:
  Successfully uninstalled ryetest-0.1.0
Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Obtaining file:///. (from -r /tmp/tmpmz3dfnl1 (line 3))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting asgiref==3.6.0 (from -r /tmp/tmpmz3dfnl1 (line 1))
  Downloading http://mirrors.tencentyun.com/pypi/packages/8f/29/38d10a47b322a77b2d12c2b79c789f52956f733cb701d4d5157c76b5f238/asgiref-3.6.0-py3-none-any.whl (23 kB)
ERROR: Ignored the following versions that require a different python version: 4.0 Requires-Python >=3.8; 4.0.1 Requires-Python >=3.8; 4.0.10 Requires-Python >=3.8; 4.0.2 Requires-Python >=3.8; 4.0.3 Requires-Python >=3.8; 4.0.4 Requires-Python >=3.8; 4.0.5 Requires-Python >=3.8; 4.0.6 Requires-Python >=3.8; 4.0.7 Requires-Python >=3.8; 4.0.8 Requires-Python >=3.8; 4.0.9 Requires-Python >=3.8; 4.0a1 Requires-Python >=3.8; 4.0b1 Requires-Python >=3.8; 4.0rc1 Requires-Python >=3.8; 4.1 Requires-Python >=3.8; 4.1.1 Requires-Python >=3.8; 4.1.2 Requires-Python >=3.8; 4.1.3 Requires-Python >=3.8; 4.1.4 Requires-Python >=3.8; 4.1.5 Requires-Python >=3.8; 4.1.6 Requires-Python >=3.8; 4.1.7 Requires-Python >=3.8; 4.1.8 Requires-Python >=3.8; 4.1a1 Requires-Python >=3.8; 4.1b1 Requires-Python >=3.8; 4.1rc1 Requires-Python >=3.8; 4.2 Requires-Python >=3.8; 4.2a1 Requires-Python >=3.8; 4.2b1 Requires-Python >=3.8; 4.2rc1 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement django==4.2 (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29, 2.0a1, 2.0b1, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.12, 2.0.13, 2.1a1, 2.1b1, 2.1rc1, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.2a1, 2.2b1, 2.2rc1, 2.2, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.17, 2.2.18, 2.2.19, 2.2.20, 2.2.21, 2.2.22, 2.2.23, 2.2.24, 2.2.25, 2.2.26, 2.2.27, 2.2.28, 3.0a1, 3.0b1, 3.0rc1, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.1a1, 3.1b1, 3.1rc1, 3.1, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.2a1, 3.2b1, 3.2rc1, 3.2, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18)
ERROR: No matching distribution found for django==4.2
Traceback (most recent call last):
  File "/home/ubuntu/.rye/self/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.rye/self/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.rye/self/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.rye/self/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.rye/self/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.rye/self/lib/python3.10/site-packages/piptools/scripts/sync.py", line 174, in cli
    sync.sync(
  File "/home/ubuntu/.rye/self/lib/python3.10/site-packages/piptools/sync.py", line 244, in sync
    run(  # nosec
  File "/home/ubuntu/.rye/py/cpython@3.10.9/install/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/ubuntu/program/python/ryetest/.venv/bin/python', '-m', 'pip', 'install', '-r', '/tmp/tmpmz3dfnl1', '--index-url', 'http://mirrors.tencentyun.com/pypi/simple', '--trusted-host', 'mirrors.tencentyun.com', '--python=/home/ubuntu/program/python/ryetest/.venv/bin/python']' returned non-zero exit status 1.
Error: Installation of dependencies failed
```

**Comment by CharlesChen0823** [comment]
I found that unearth cannot find the requirements with specify the python version.
