### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by anna-hope** [mitsuhiko/rye#655]
### Steps to Reproduce

1. Have an existing project with a `setup.py` file
2. Run `rye init`

The `setup.py` is extremely simple:

```
from setuptools import setup

# See setup.cfg file

if __name__ == "__main__":
    setup()
```

I know the docs say "Note that Rye today does not support setup.py based projects," but also I found [this issue](https://github.com/mitsuhiko/rye/issues/191), which suggests `rye init` should work in some capacity. 

I guess `rye init --no-import` could be a workaround, but that would complicate the project setup. 

I also uninstalled and re-installed Rye to make sure it wasn't some issue with my installation.

### Expected Result

The project can be initialized successfully.

### Actual Result

```
error: failed to proxy setup.py
Traceback (most recent call last):
  File "/Users/annahope/<project>/./setup.py", line 2, in <module>
    from setuptools import setup
  File "/var/folders/b6/nm_w0grs5vx0_xq0tpsvft6h0000gn/T/.tmpmXonDM/setuptools.py", line 12, in <module>
    import setuptools as __setuptools
  File "/var/folders/b6/nm_w0grs5vx0_xq0tpsvft6h0000gn/T/.tmpmXonDM/setuptools.py", line 12, in <module>
    import setuptools as __setuptools
ModuleNotFoundError: No module named 'setuptools'
```

### Version Info

rye 0.23.0
commit: 0.23.0 (0fdcdda6c 2024-02-13)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true

**Comment by mitsuhiko** [comment]
The import doesn't really work today for `setupl.py` based projects, at least not well enough. You probably can make some progress by running `rye init --build-system=setuptools`.

**Comment by anna-hope** [comment]
@mitsuhiko `rye init --build-system=setuptools` has the same issue. But, thank you for clarifying that the import doesn't work at the moment. I'll try to proceed with `rye init --no-import`.

**Comment by willfrey** [comment]
I ran into this same issue and was able to use `pip` to install `setuptools` into the `rye` virtual environment located at `~/.rye/self` (at least for me with a default installation).

```shell
cd ~/.rye/self
./bin/pip install setuptools
```

Not ideal to be manually installing packages into the `rye`-managed virtual environment, but it did work.

**Comment by WinChua** [comment]
The same as me. And with some research, it seems that it's because setuptools is not been installed when create a venv by default since python 3.12. So is that worth to execute `pip install setuptools` automaticlly when we use python3.12

[what's new in python 3.12](https://docs.python.org/3/whatsnew/3.12.html#ensurepip)
[Remove bundled setuptools](https://github.com/python/cpython/issues/95299)

**Comment by sbor23** [comment]
This also happens with python 3.10.

**Comment by cvdub** [comment]
+1 for this issue. rye isn't able to install some versions of numpy on Python 3.12:
```
Building numpy==1.24.4
  × Failed to download and build `numpy==1.24.4`
  ╰─▶ Build backend failed to determine requirements with `build_wheel()`
      (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 8, in <module>
        File
      "/Users/cjv/Library/Caches/uv/builds-v0/.tmpNo2TnG/lib/python3.12/site-packages/setuptools/__init__.py",
      line 10, in <module>
          import distutils.core
      ModuleNotFoundError: No module named 'distutils'

      hint: `distutils` was removed from the standard library in Python 3.12.
      Consider adding a constraint (like `numpy >1.24.4`) to avoid building a
      version of `numpy` that depends on `distutils`.
```

Despite `[build-system]` in `pyproject.toml` indicating that setuptools is required.

```
[build-system]
requires = [
    "setuptools >= 61.0.0",
    "setuptools_scm[toml] >= 4",
    "setuptools_scm_git_archive",
    "wheel >= 0.37.0",
]
```
