### ISSUE TITLE
Windows: tools shim does not work properly

### ISSUE THREAD

**Issue by j178** [mitsuhiko/rye#696]
### Steps to Reproduce

```sh
> gcm ipython
Get-Command: The term 'ipython' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

> rye tools install ipython -f
Resolved 15 packages in 605ms
Installed 15 packages in 288ms
 + asttokens==2.4.1
 + colorama==0.4.6
 + decorator==5.1.1
 + executing==2.0.1
 + ipython==8.21.0
 + jedi==0.19.1
 + matplotlib-inline==0.1.6
 + parso==0.8.3
 + prompt-toolkit==3.0.43
 + pure-eval==0.2.2
 + pygments==2.17.2
 + six==1.16.0
 + stack-data==0.6.3
 + traitlets==5.14.1
 + wcwidth==0.2.13

Installed scripts:
  - ipython
  - ipython3

note: additional scripts were encountered in non-installed dependencies.

> gcm ipython

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ipython.exe                                        0.0.0.0    C:\Users\nigel\.rye\shims\ipython.exe

> ls C:\Users\nigel\.rye\shims\ipython.exe

    Directory: C:\Users\nigel\.rye\shims

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---           2024/2/20     2:03              0 ipython.exe -> C:\Users\nigel\.rye\tools\ipython\Scripts\ipython.exe

> ipython
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nigel\.rye\shims\ipython.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'IPython'
```

### Expected Result

`ipython` runs successfully.

### Actual Result
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nigel\.rye\shims\ipython.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'IPython'
```
### Version Info

rye 0.25.0
commit: 0.24.0+25 (522865cb4 2024-02-19)
platform: windows (x86_64)
self-python: cpython@3.12
symlink support: true

### Stacktrace

I added some `dbg!` statements to debug:
<details>
<summary>The `dbg!` patch</summary>

```patch
diff --git forkSrcPrefix/rye/src/cli/shim.rs forkDstPrefix/rye/src/cli/shim.rs
index c74757f32eda6e31a6a24e30e3b9fe200b2ebeda..17ed06340434f5466d4528117cbdf3461bcb2f04 100644
--- forkSrcPrefix/rye/src/cli/shim.rs
+++ forkDstPrefix/rye/src/cli/shim.rs
@@ -26,7 +26,7 @@ fn detect_shim(args: &[OsString]) -> Option<String> {
         return None;
     }
 
-    let path = env::current_exe().ok()?;
+    let path = dbg!(env::current_exe().ok()?);
     let shim_name = path.file_name()?;
 
     // rye is itself placed in the shims folder, so it must not
@@ -182,7 +182,7 @@ fn get_shim_target(
     pyproject: Option<&PyProject>,
 ) -> Result<Option<Vec<OsString>>, Error> {
     // if we can find a project, we always look for a local virtualenv first for shims.
-    if let Some(pyproject) = pyproject {
+    if let Some(pyproject) = dbg!(pyproject) {
         // However we only allow automatic synching, if we are rye managed.
         if pyproject.rye_managed() {
             let _guard = redirect_to_stderr(true);
@@ -201,6 +201,7 @@ fn get_shim_target(
         let mut args = args.to_vec();
         let folder = pyproject.venv_path().join(VENV_BIN);
         if let Some(m) = which::which_in_global(target, Some(&folder))?.next() {
+            dbg!(&args, &folder, &m);
             args[0] = m.into();
             return Ok(Some(args));
         }
@@ -224,7 +225,7 @@ fn get_shim_target(
         }
 
     // Global shims (either implicit or requested)
-    } else if is_python_shim(target) {
+    } else if dbg!(is_python_shim(target)) {
         let config = Config::current();
         let mut remove1 = false;
 
@@ -239,7 +240,7 @@ fn get_shim_target(
                     .context("invalid Python version requested from command line")?,
                 false,
             )
-        } else if config.global_python() {
+        } else if dbg!(config.global_python()) {
             (
                 match get_python_version_request_from_pyenv_pin(&std::env::current_dir()?) {
                     Some(version_request) => version_request,
@@ -250,7 +251,7 @@ fn get_shim_target(
         } else {
             // if neither requested explicitly, nor global-python is enabled, we fall
             // back to the next shadowed target
-            return find_shadowed_target(target, args);
+            return dbg!(find_shadowed_target(target, args));
         };
 
         let py_ver = latest_available_python_version(&version_request)
@@ -279,7 +280,7 @@ fn get_shim_target(
 
     // if we make it this far, we did not find a shim in the project, look for
     // a global one instead.
-    find_shadowed_target(target, args)
+    dbg!(find_shadowed_target(target, args))
 }
 
 fn spawn_shim(args: Vec<OsString>) -> Result<Infallible, Error> {
@@ -311,9 +312,10 @@ fn matches_shim(s: &str, reference: &str) -> bool {
 /// This replaces ourselves with the shim target for when the
 /// executable is invoked as a shim executable.
 pub fn execute_shim(args: &[OsString]) -> Result<(), Error> {
-    if let Some(shim_name) = detect_shim(args) {
+    dbg!(args);
+    if let Some(shim_name) = dbg!(detect_shim(args)) {
         let pyproject = PyProject::discover().ok();
-        if let Some(args) = get_shim_target(&shim_name, args, pyproject.as_ref())? {
+        if let Some(args) = dbg!(get_shim_target(&shim_name, args, pyproject.as_ref())?) {
             match spawn_shim(args)? {}
         } else if is_python_shim(&shim_name) {
             if pyproject.is_some() {

```
</details>

This is the output when executing `ipython`:
```sh
> ipython
[rye\src\cli\shim.rs:316:5] args = [
    "C:\\Users\\nigel\\.rye\\shims\\python.exe",
    "C:\\Users\\nigel\\.rye\\shims\\ipython.exe",
]
[rye\src\cli\shim.rs:30:16] env::current_exe().ok()? = "C:\\Users\\nigel\\.rye\\shims\\python.exe"
[rye\src\cli\shim.rs:317:30] detect_shim(args) = Some(
    "python.exe",
)
[rye\src\cli\shim.rs:186:30] pyproject = None
[rye\src\cli\shim.rs:229:15] is_python_shim(target) = true
[rye\src\cli\shim.rs:244:19] config.global_python() = true
[rye\src\cli\shim.rs:319:29] get_shim_target(&shim_name, args, pyproject.as_ref())? = Some(
    [
        "C:\\Users\\nigel\\.rye\\py\\cpython@3.12.1\\install\\python.exe",
        "C:\\Users\\nigel\\.rye\\shims\\ipython.exe",
    ],
)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nigel\.rye\shims\ipython.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'IPython'
```

The first line 
```
[rye\src\cli\shim.rs:316:5] args = [
    "C:\\Users\\nigel\\.rye\\shims\\python.exe",
    "C:\\Users\\nigel\\.rye\\shims\\ipython.exe",
]
```
seems pretty weird. How does the `ipython` command line become `C:/Users/nigel/.rye/shims/python.exe C:/Users/nigel/.rye/shims/ipython.exe`?

This issue can be reproduced with any other installed tools, like `black`:
```sh
> black
[rye\src\cli\shim.rs:316:5] args = [
    "C:\\Users\\nigel\\.rye\\shims\\python.exe",
    "C:\\Users\\nigel\\.rye\\shims\\black.exe",
]
[rye\src\cli\shim.rs:30:16] env::current_exe().ok()? = "C:\\Users\\nigel\\.rye\\shims\\python.exe"
[rye\src\cli\shim.rs:317:30] detect_shim(args) = Some(
    "python.exe",
)
[rye\src\cli\shim.rs:186:30] pyproject = None
[rye\src\cli\shim.rs:229:15] is_python_shim(target) = true
[rye\src\cli\shim.rs:244:19] config.global_python() = true
[rye\src\cli\shim.rs:319:29] get_shim_target(&shim_name, args, pyproject.as_ref())? = Some(
    [
        "C:\\Users\\nigel\\.rye\\py\\cpython@3.12.1\\install\\python.exe",
        "C:\\Users\\nigel\\.rye\\shims\\black.exe",
    ],
)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nigel\.rye\shims\black.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'black'
```

**Comment by j178** [comment]
Running from CMD results in a slight different error then PowerShell:
```sh
CMD> black
[rye\src\cli\shim.rs:316:5] args = [
    "C:\\Users\\nigel\\.rye\\shims\\python.exe",
    "black",
]
[rye\src\cli\shim.rs:30:16] env::current_exe().ok()? = "C:\\Users\\nigel\\.rye\\shims\\python.exe"
[rye\src\cli\shim.rs:317:30] detect_shim(args) = Some(
    "python.exe",
)
[rye\src\cli\shim.rs:186:30] pyproject = None
[rye\src\cli\shim.rs:229:15] is_python_shim(target) = true
[rye\src\cli\shim.rs:244:19] config.global_python() = true
[rye\src\cli\shim.rs:319:29] get_shim_target(&shim_name, args, pyproject.as_ref())? = Some(
    [
        "C:\\Users\\nigel\\.rye\\py\\cpython@3.12.1\\install\\python.exe",
        "black",
    ],
)
C:\Users\nigel\.rye\py\cpython@3.12.1\install\python.exe: can't open file 'C:\\Users\\nigel\\black': [Errno 2] No such file or directory
```

**Comment by bb010g** [comment]
I'm experiencing some different breakage with shims on 1036b043b:

```
PS C:\Users\bb010g> rye --version
rye 0.25.0
commit: unknown (1036b043b 2024-02-19)
platform: windows (x86_64)
self-python: cpython@3.12
symlink support: true
PS C:\Users\bb010g> rye tools list -v -i
pipx (1.4.3)
  pipx
PS C:\Users\bb010g> rye config --get "behavior.use-uv"
true
PS C:\Users\bb010g> rye config --get "behavior.global-python"
false
PS C:\Users\bb010g> Get-Command pipx

CommandType    Name        Version    Source
-----------    ----        -------    ------
Application    pipx.exe    0.0.0.0    C:\Users\bb010g\.rye\shims\pipx.exe

PS C:\Users\bb010g> pipx --version
error: Target Python binary 'python.exe' not found.
You are currently outside of a project. To resolve this, consider enabling global shims. Global shims allow for a Rye-managed Python installation.
For more information: https://rye-up.com/guide/shims/#global-shims
PS C:\Users\bb010g> & "${Env:USERPROFILE}\.rye\shims\pipx.exe" --version
error: Target Python binary 'python.exe' not found.
You are currently outside of a project. To resolve this, consider enabling global shims. Global shims allow for a Rye-managed Python installation.
For more information: https://rye-up.com/guide/shims/#global-shims
PS C:\Users\bb010g> & "${Env:USERPROFILE}\.rye\tools\pipx\Scripts\pipx.exe" --version
1.4.3
PS C:\Users\bb010g> rye config --set-bool "behavior.global-python=true"
PS C:\Users\bb010g> pipx --version
error: failed to get default toolchain

Caused by:
    invalid syntax for version
PS C:\Users\bb010g> & "${Env:USERPROFILE}\.rye\shims\pipx.exe" --version
error: failed to get default toolchain

Caused by:
    invalid syntax for version
PS C:\Users\bb010g> & "${Env:USERPROFILE}\.rye\tools\pipx\Scripts\pipx.exe" --version
1.4.3
```

It looks like the symbolic linking of tool script shims into `.rye/shims` is throwing things off.

**Comment by mitsuhiko** [comment]
This might be fixed by a newer uv version. If you can please try with master, otherwise wait for the next release.

**Comment by j178** [comment]
I tested it with the master branch (using uv==0.15), yet the error persists unchanged.

**Comment by j178** [comment]
@bb010g Hi, for your case, can you the result of `rye config --get default.toolchain`?

**Comment by mitsuhiko** [comment]
I don't have a windows machine at the moment to test. It would be good to find out if this is something that is a bug on the uv side or here.

uv writes the launcher for windows here, I did not look yet into how it works.

https://github.com/astral-sh/uv/blob/d05cb8464a933a4b8e1ebe39988e0209da73ed19/crates/install-wheel-rs/src/wheel.rs#L299-L305

**Comment by j178** [comment]
Posted it to `uv` too https://github.com/astral-sh/uv/issues/1766

**Comment by bb010g** [comment]
> Hi, for your case, can you show the result of `rye config --get default.toolchain`?

@j178 Sure. Here's the transcript for that, just after updating to 33454c499:

```
PS C:\Users\bb010g> rye --version
rye 0.26.0
commit: unknown (33454c499 2024-02-21)
platform: windows (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: true
PS C:\Users\bb010g> rye config --get "default.toolchain"
cpython@latest
PS C:\Users\bb010g> rye tools install pycowsay
Detected outdated rye internals. Refreshing
Bootstrapping rye internals
Found a compatible Python version: cpython@3.12.1
Upgrading pip
Installing internal dependencies
Resolved 1 package in 261ms
Downloaded 1 package in 30ms
Installed 1 package in 13ms
 + pycowsay==0.0.0.2

Installed scripts:
  - pycowsay
PS C:\Users\bb010g> pycowsay
error: failed to get default toolchain

Caused by:
    invalid syntax for version
PS C:\Users\bb010g> & "${Env:USERPROFILE}\.rye\shims\pycowsay.exe"
error: failed to get default toolchain

Caused by:
    invalid syntax for version
PS C:\Users\bb010g> & "${Env:USERPROFILE}\.rye\tools\pycowsay\Scripts\pycowsay.exe"
C:\Users\bb010g\.rye\tools\pycowsay\Lib\site-packages\pycowsay\main.py:23: SyntaxWarning: invalid escape sequence '\ '
  """


<  >

   \   ^__^
    \  (oo)\_______
       (__)\       )\/\
           ||----w |
           ||     ||

```

**Comment by j178** [comment]
@bb010g 
```
PS C:\Users\bb010g> rye config --get "default.toolchain"
cpython@latest
```
I believe that `cpython@latest` is not supported as a valid toolchain name currently, it should be a standard semver.
