### ISSUE TITLE
rye sync should not require README.md file

### ISSUE THREAD

**Issue by wasdee** [mitsuhiko/rye#83]
### Steps to Reproduce

https://github.com/wasdee/ped4you-cross-detection/blob/main/Dockerfile.rye

```
FROM rust:latest

RUN cargo install --git https://github.com/mitsuhiko/rye rye

WORKDIR /usr/src/app

COPY requirements*.lock pyproject.toml ./
RUN rye sync

COPY main.py ./
COPY models/model2.pkl ./models/

EXPOSE 8000

CMD rye run serve
```

### Expected Result

`COPY requirements*.lock pyproject.toml  ./`
no readme.md needed

### Actual Result

```
 => ERROR [5/7] RUN rye sync                                                                               24.1s
------                                                                                                           
 > [5/7] RUN rye sync:                                                                                           
#9 0.420 Bootstrapping rye internals                                                                             
#9 0.421 Downloading cpython@3.10.9                                                                              
#9 5.419 success: Downloaded cpython@3.10.9                                                                      
#9 12.56 Upgrading pip                                                                                           
#9 13.22 Installing internal dependencies
#9 16.86 Downloading cpython@3.11.1
#9 21.37 success: Downloaded cpython@3.11.1
#9 21.38 Initializing new virtualenv in /usr/src/app/.venv
#9 21.38 Python version: cpython@3.11.1
#9 21.79 Generating production lockfile: /usr/src/app/requirements.lock
#9 23.91     error: subprocess-exited-with-error
#9 23.91     
#9 23.91     × Preparing metadata (pyproject.toml) did not run successfully.
#9 23.91     │ exit code: 1
#9 23.91     ╰─> [18 lines of output]
#9 23.91         Traceback (most recent call last):
#9 23.91           File "/root/.rye/self/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#9 23.91             main()
#9 23.91           File "/root/.rye/self/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#9 23.91             json_out['return_val'] = hook(**hook_input['kwargs'])
#9 23.91           File "/root/.rye/self/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
#9 23.91             whl_basename = backend.build_wheel(metadata_directory, config_settings)
#9 23.91           File "/tmp/pip-build-env-frn1ltt3/overlay/lib/python3.10/site-packages/hatchling/build.py", line 56, in build_wheel
#9 23.91             return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
#9 23.91           File "/tmp/pip-build-env-frn1ltt3/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 93, in build
#9 23.91             self.metadata.validate_fields()
#9 23.91           File "/tmp/pip-build-env-frn1ltt3/overlay/lib/python3.10/site-packages/hatchling/metadata/core.py", line 244, in validate_fields
#9 23.91             self.core.validate_fields()
#9 23.91           File "/tmp/pip-build-env-frn1ltt3/overlay/lib/python3.10/site-packages/hatchling/metadata/core.py", line 1325, in validate_fields
#9 23.91             getattr(self, attribute)
#9 23.91           File "/tmp/pip-build-env-frn1ltt3/overlay/lib/python3.10/site-packages/hatchling/metadata/core.py", line 508, in readme
#9 23.91             raise OSError(message)
#9 23.91         OSError: Readme file does not exist: README.md
#9 23.91         [end of output]
```

### Version Info

rye --version                                                                                                  
rye 0.1.0
commit: unknown (c8e50e58d 2023-04-30)
platform: linux (x86_64)
self-python: cpython@3.10

**Comment by mitsuhiko** [comment]
It does not require a readme.md file. It might still be referenced by your pyproject.toml. Deleting the reference there should resolve it.

**Comment by wasdee** [comment]
Thank you for workaround.


For my context, `rye init` was creating the `pyproject.toml`. and i've not modified it myself in anyway. are you @mitsuhiko expecting this? if no,feel free to reopen issue for the future PR ref.

**Comment by mitsuhiko** [comment]
It should have also created a `README.md` file though.
